# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := samp-chatbot

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

samp-chatbot: 
	@echo "==== Building samp-chatbot ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f samp-chatbot.make

clean:
	@${MAKE} --no-print-directory -C . -f samp-chatbot.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   samp-chatbot"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
